### ISSUE TITLE
No Validation of Negative Balance Inputs 

### ISSUE THREAD

**Issue by annasshaikh** [annasshaikh/BankingBoy#2]
### What if someone while depositing entrees negative balance?  
balance[account_number] += input.nextInt();  
This Would Decrease the balance not increase it.  
_Btw We can take revenge from our silly partners._   
### Hack the System By Entering a Negative Value on the Withdrawal Part.
balance[account_number] -= input.nextInt();  
This Would Increase the balance not decrease it.  
_You get 2X Amount free one cash at hand second cash at bank_

**Comment by itbaans** [comment]
Issue resolved
